#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#
# Configuration
font_size			            12
remember_window_size		      yes
scrollback_lines            	2000
wheel_scroll_min_lines      	1
enable_audio_bell		         yes
background_opacity		      0.7
hide_window_decorations    	yes
dynamic_background_opacity  	yes
confirm_os_window_close		   0
cursor_blink_interval       	0.5
cursor_stop_blinking_after    0	
initial_window_width        	1200
initial_window_height       	700

shell_integration             enabled
allow_remote_control          yes

cursor_trail 			         5
cursor_trail_start_threshold	2


# BEGIN_KITTY_THEME
# Gruvbox Material Dark Hard
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="DepartureMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
